language: objective-c
osx_image: xcode7.3

branches:
  only:
    - master
    - develop

env:
  global:
    - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=1
    - BUILD_TARGET="-scheme hackfoldr-iOS -sdk iphonesimulator"

before_install:
    - gem install xcpretty -N --no-ri --no-rdoc

script:
  - set -o pipefail
  - xcodebuild clean test -workspace hackfoldr-iOS.xcworkspace $BUILD_TARGET | xcpretty
