language: objective-c
xcode_workspace: hackfoldr-iOS.xcworkspace
xcode_scheme: hackfoldr-iOS
osx_image: xcode7.3

branches:
  only:
    - master
    - develop

before_install:
#    - brew install xctool
    - git clone https://github.com/facebook/xctool.git

script:
  - xctool/xctool.sh -sdk iphonesimulator -configuration "DEBUG" build
  - xctool/xctool.sh -sdk iphonesimulator build-tests
  - xctool/xctool.sh -sdk iphonesimulator run-tests
