language: objective-c
osx_image: xcode7.3

branches:
  only:
    - master
    - develop

script:
  - xctool -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator -configuration "DEBUG" CONFIGURATION_BUILD_DIR='~/build/' build
  - xctool -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator CONFIGURATION_BUILD_DIR='~/build/' build-tests
  - xctool -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator CONFIGURATION_BUILD_DIR='~/build/' run-tests
