language: objective-c

script:
  - xctool -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator -configuration "DEBUG" CONFIGURATION_BUILD_DIR='~/build/' build
  - xctool -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator -configuration "DEBUG" CONFIGURATION_BUILD_DIR='~/build/' build-tests