language: objective-c
osx_image: xcode7.3

branches:
  only:
    - master
    - develop

before_install:
    - git clone --depth=1 https://github.com/facebook/xctool.git

script:
  - travis_wait 30 xctool/xctool.sh -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator -configuration "DEBUG" build
  - travis_wait 30 xctool/xctool.sh -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator build-tests
  - travis_wait 30 xctool/xctool.sh -workspace hackfoldr-iOS.xcworkspace -scheme hackfoldr-iOS -sdk iphonesimulator run-tests
